### PR TITLE
Add a cursed example to Unsafe 1

### LINKED ISSUE #38: Make unsafe 1 worse
@Amanieu said that someone suggested also adding an example to unsafe 1 that says `(*null,)`. please give us a GitHub handle to credit Amanieu 😊👉👈

### PR DESCRIPTION
**Pull request by WaffleLapkin**
Resolves #38
Thanks @Amanieu
r? Nora

### CODE REVIEW

**Review by Nilstrieb — CHANGES_REQUESTED** [review]
wait for the username to credit

**Comment by WaffleLapkin** [comment]
Someone needs to regenerate the stderr tests and that can't be me because I'm dumb and bad and don't know how to install the right compiler

**Comment by Amanieu** [comment]
This was suggested by @Victoronz

**Comment by WaffleLapkin** [comment]
I ascended, written a [tool](https://github.com/wafflelapkin/rustdn) to install the right compiler, and regenerated stderr files.

**Review by Noratrieb — APPROVED** [review]
if waffle says its good it must be good

**Comment by WaffleLapkin** [comment]
Don't trust me :(

**Comment by Noratrieb** [comment]
i do!!!

**Comment by Noratrieb** [comment]
:3

**Comment by Noratrieb** [comment]
:3

**Pull request merged**
